# version format
version: 1.1.8.{build}

image: Visual Studio 2022

environment:
  EnableNuGetPackageRestore: true

dotnet_csproj:
  patch: true
  file: 'ShippingRates\*.csproj'
  version: '{version}'

# build configuration
build:
  project: ShippingRates.sln    # path to Visual Studio solution or project
  publish_nuget: true           # package projects with .nuspec files and push to artifacts

  # MSBuild verbosity level
  verbosity: normal

# scripts to run before build
before_build:
  - nuget restore